#Default Profile
logging.level:
  org.hibernate: INFO  
  org.springframework: ERROR
  org.springframework.boot.context.embedded: INFO
  com.learning.springboot: INFO
#Setting Profile
spring.profiles.active: unit-test 
---
#Local Profile
server.port: 8080
spring:
  profiles: local
  application.name: party-service-app
  jpa:
    generate-ddl: true
    show-sql: true    
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        #ddl-auto: create
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost/party-service-app-db
    username: root
    password:
    platform: mysql 
management:
  #port: 8080
  security:
    enabled: false      
---
#Unit Test Profile using H2 In Memory Database
spring:
  profiles: unit-test
  application:
    name: party-service-dev
  # To See H2 Console in Browser:
  # http://localhost:<<Port>>/h2-console
  # Enabling H2 Console
  h2:
    console:
      enabled: true
  jpa:
    generate-ddl: true
    show-sql: true    
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        ddl-auto: create
  datasource:
    url: jdbc:h2:mem:party-service-app-db;DB_CLOSE_ON_EXIT=FALSE  
    driverClassName: org.h2.Driver
    username: sa
    password:
    platform: h2
server.port: 8080
---
#PCF Profile
spring:
  profiles: pcf
  application.name: party-service-app
  jpa:
    generate-ddl: true
    show-sql: true    
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        #ddl-auto: create
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost/party-service-app-db?createDatabaseIfNotExist=true&autoReconnect=true&useSSL=false
    username: root
    password:
    platform: mysql
#Enabling Random Vacant Port assignment
server.port: ${PORT:0}
management:
  #port: 8080
  security:
    enabled: false  